#' Project matrix after optimization
#'
#' After the MAP permutation was found with [find_MAP()],
#' use this permutation to approximate the covariance matrix
#' with bigger statistical confidence.
#'
#' Project matrix on the space of symmetrical matrices invariant
#' by a cyclic group generated by `perm`.
#' This implements the formal
#' [Definition 3 from references](https://arxiv.org/abs/2004.03503).
#'
#' When `S` is the sample covariance matrix (output of `cov()` function, see
#' examples), then `S` is the **unbiased estimator** of the covariance matrix.
#' However, the **maximum likelihood estimator** of the covariance matrix is
#' `S*(n-1)/(n)`, unless n < p, when the
#' **maximum likelihood estimator does not exist**. For more information, see
#' [Wikipedia - Estimation of covariance matrices](https://en.wikipedia.org/wiki/Estimation_of_covariance_matrices).
#'
#' The maximum likelihood estimator differs when one knows the covariance
#' matrix is **invariant under some permutation**. This estimator will
#' be symmetric AND have some values repeated (see examples and
#' [Corollary 12 from references](https://arxiv.org/abs/2004.03503)).
#'
#' The estimator will be invariant under the given permutation. Also, it
#' will **need fewer observations** for the maximum likelihood estimator to
#' exist (see **Project Matrix - Equation (6)** section in
#' `vignette("Theory", package = "gips")` or in its
#' [pkgdown page](https://przechoj.github.io/gips/articles/Theory.html)).
#' For some permutations, even \eqn{n = 2} could be enough.
#' The minimal number of observations needed is named `n0` and
#' can be calculated by `summary.gips()`.
#'
#' For more details, see the **Project Matrix - Equation (6)**
#' section in `vignette("Theory", package = "gips")` or in its
#' [pkgdown page](https://przechoj.github.io/gips/articles/Theory.html).
#'
#' @param S A square matrix to be projected.
#'     The empirical covariance matrix.
#'     (See the `S` parameter in the `gips()` function).
#'     When it is not positive semi-definite,
#'     it shows a warning of a class `not_positive_semi_definite_matrix`.
#' @param perm A permutation to be projected on.
#'     An object of a `gips` class,
#'     a `gips_perm` class, or anything that can be used
#'     as the `x` argument in the `gips_perm()` function.
#'
#' @returns The matrix `S` projected on the space of symmetrical matrices invariant
#' by a cyclic group generated by `perm`. See Details for more.
#' @export
#'
#' @seealso
#' * [Wikipedia - Estimation of covariance matrices](https://en.wikipedia.org/wiki/Estimation_of_covariance_matrices)
#' * **Project Matrix - Equation (6)** section of
#'     `vignette("Theory", package = "gips")` or its
#'     [pkgdown page](https://przechoj.github.io/gips/articles/Theory.html) -
#'     A place to learn more about the math
#'     behind the `gips` package and see
#'     more examples of `project_matrix()`.
#' * [find_MAP()] - The function that finds
#'     the Maximum A Posteriori (MAP) Estimator
#'     for a given `gips` object.
#'     After the MAP Estimator is found, the matrix
#'     `S` can be projected on this permutation,
#'     creating the MAP Estimator of the covariance matrix
#'     (see examples).
#' * [gips_perm()] - Constructor for the `perm` parameter.
#' * [plot.gips()] - For `plot(g, type = "MLE")`,
#'     the `project_matrix()` is called (see examples).
#' * [summary.gips()] - Can calculate the `n0`, the minimal
#'     number of observations, so that the projected matrix
#'     will be the MLE estimator of the covariance matrix.
#'
#' @examples
#' p <- 6
#' my_perm <- "(14)(23)" # permutation (1,4)(2,3)(5)(6)
#' number_of_observations <- 10
#' X <- matrix(rnorm(p * number_of_observations), number_of_observations, p)
#' S <- cov(X)
#' projected_S <- project_matrix(S, perm = my_perm)
#' projected_S
#' # The value in [1,1] is the same as in [4,4]; also, [2,2] and [3,3];
#'   # also [1,2] and [3,4]; also, [1,5] and [4,5]; and so on
#'
#' # Plot the projected matrix:
#' g <- gips(S, number_of_observations, perm = my_perm)
#' plot(g, type = "MLE")
#'
#' # Find the MAP Estimator of covariance
#' g_MAP <- find_MAP(g, max_iter = 10, show_progress_bar = FALSE, optimizer = "Metropolis_Hastings")
#' S_MAP <- project_matrix(attr(g, "S"), perm = g_MAP)
#' S_MAP
#' plot(g_MAP, type = "heatmap")
project_matrix <- function(S, perm) {
  if (!is.matrix(S)) {
    rlang::abort(c("There was a problem identified with the provided arguments:",
      "i" = "`S` must be a matrix.",
      "x" = paste0(
        "You provided `S` with `class(S) == (",
        paste(class(S), collapse = ", "),
        ")`."
      )
    ))
  }
  if (nrow(S) != ncol(S)) {
    rlang::abort(c("There was a problem identified with the provided arguments:",
      "i" = "`S` must be a square matrix.",
      "x" = paste0(
        "You provided `S` as a matrix, but with different sizes: ",
        nrow(S), " and ", ncol(S), "."
      )
    ))
  }
  if (!is.positive.semi.definite.matrix(S)) {
    rlang::warn(c(
      "i" = "`project_matrix()` is designed for positive semi-definite matrices",
      "x" = "You provided `S` that is not positive semi-definite matrix",
      "*" = "`gips` can still project this matrix on the provided permutation",
      "i" = "Did You provide the wrong `S` matrix?"
    ), class = "not_positive_semi_definite_matrix")
  }

  perm_size <- ncol(S)
  if (!inherits(perm, "gips_perm")) {
    perm <- gips_perm(perm, perm_size)
  } else if (attr(perm, "size") != ncol(S)) {
    rlang::abort(c("There was a problem identified with the provided arguments:",
      "i" = "Size of `perm` must be equal to number of columns and rows of `S`.",
      "x" = paste0(
        "You provided `perm` with `size == ",
        attr(perm, "size"),
        "`, but the `S` matrix has ",
        ncol(S), " columns."
      )
    ))
  }

  project_matrix_cpp_(S, perm)
}

#' @noRd
project_matrix_cpp_ <- function(S, perm) {
  project_matrices_cpp_(list(S), perm)[[1]]
}

#' @noRd
project_matrices_cpp_ <- function(matrices, perm) {
  projected_matrices <- project_matrices_cpp_impl_(matrices, perm_to_sigma_(perm))
  names(projected_matrices) <- names(matrices)

  for (i in seq_along(projected_matrices)) {
    colnames(projected_matrices[[i]]) <- colnames(matrices[[i]])
    rownames(projected_matrices[[i]]) <- rownames(matrices[[i]])
  }

  projected_matrices
}

#' Convert a `gips_perm` object to a 1-based permutation vector
#'
#' @noRd
perm_to_sigma_ <- function(perm) {
  sigma <- seq_len(attr(perm, "size"))

  for (cycle in perm) {
    sigma[cycle] <- c(cycle[-1], cycle[1])
  }

  sigma
}
