# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

project_matrix_cpp_impl_ <- function(S, sigma) {
    .Call(`_gips_project_matrix_cpp_impl_`, S, sigma)
}

