# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

project_matrices_cpp_impl_ <- function(matrices, sigma) {
    .Call(`_gips_project_matrices_cpp_impl_`, matrices, sigma)
}

